### ISSUE TITLE
Future of bscp

### ISSUE THREAD

**Issue by vog** [bscp-tool/bscp#16]
I'd like to hear opinions about the future development of the `bscp` tool.

Bscp was initially created to fill a gap where Rsync had a really bad performance back then: Backing up single, large block devices over the network, transferring only changed blocks. This was useful to transfer disk images of virtual machines, even encrypted ones.

Regarding #14, Rsync seems to have caught up meanwhile, so maybe this tool is no longer needed at all?

In case there are still users who have important use cases for Bscp: Would anyone step up to take maintainership of this project? I'm willing to create an organization on GitHub and to move Bscp to it, given that one or two people join in.

Otherwise, I'd propose to close and archive this project, and to put a notice into the README redirecting people to Rsync.

What do you think?

**Comment by romanrm** [comment]
Last time I checked rsync still didn't support working with block devices directly. So I don't see how the usage of rsync described in #14, requiring highly elaborate scripting of hacks like "Use dd to read the chunk from the snapshot, and write to a ramdrive on the local system, Use ssh to the remote system, and use dd to read the chunk from the remote LV to a ramdrive on the remote" translates into "bscp is no longer needed, we all can just use rsync now".

If the above process had been published as a (quality, convenient and well-debugged) wrapper, then perhaps, but even then, the mentioned 1G chunks seem to be way too large to be optimal, and with say 1M chunks, there will be thousands of "dd" invocations per copy, which is likely to have a significant toll on performance by itself.

**Comment by vog** [comment]
@romanrm Thanks a lot for pointing this out!

I didn't see that, and this demonstrates once more that this project needs maintainers who actually use Bscp in their daily lives, which is unfortunately no longer true for me. (Over the years I solved my backups using entirely different concepts, using ZFS and similar stuff.)

But your comment also means that Bscp still does have use cases, and does have users who care, which makes me happy.

So my question to the round still stand:

* Who would like to stand up to take maintainership?

(Ideally, 2 or more people, and of course I'll hand over gradually, and I'll be available in the future for any organizational issues - just not for review and testing.)

**Comment by glaweh** [comment]
@vog: I just discovered bscp, needing a rsync-like solution for block devices (FC-SAN-manufacturer failed).
a major issue of bscp is that block-checksums  on source and target are not done simultanously, which in the
end doubles the runtim

**Comment by glaweh** [comment]
bscp is <200 lines of code, so I could jump in as a maintainer. IRL, I am also using the ZFS/sanoid/syncoid  triple for the backups of our 'data' volumes

**Comment by glaweh** [comment]
problems are windows systems in our proxmox cluster (with thick-LVM), where only ```dd``` or ```bscp``` could help :(

**Comment by vog** [comment]
@glaweh Thanks a lot for stepping up! I'll transform `bscp` into a community project as soon as possible.

**Comment by vog** [comment]
FYI: I just cleaned up the project setup a bit, see #21.

**Comment by vog** [comment]
It seems that I'll have to keep being the maintainer of this project for now, closing issues at a very slow but steady pace.

Help is still welcome, and I'm still open to hand this project over to a more active contributor to likes to become a maintainer.
